//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TCP:192.168.10.5;Initial Catalog=OdinDB;Integrated Security=True;Conn" +
            "ect Timeout=3000")]
        public string OdinDBConnectionStringHome {
            get {
                return ((string)(this["OdinDBConnectionStringHome"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TCP:192.168.10.5;Initial Catalog=OdinDB;Persist Security Info=True;Us" +
            "er ID=AISQL;Password=qwerty")]
        public string OdinDBConnectionStringHomeNetwork {
            get {
                return ((string)(this["OdinDBConnectionStringHomeNetwork"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.5;Initial Catalog=OdinDB;Persist Security Info=True;User I" +
            "D=AI_Remote;Password=Aisql18!")]
        public string OdinDBConnectionStringRemote {
            get {
                return ((string)(this["OdinDBConnectionStringRemote"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TCP:192.168.10.5, 1433;Initial Catalog=OdinDB;Integrated Security=Tru" +
            "e;Connect Timeout=3000")]
        public string OdinDBConnectionStringSMD {
            get {
                return ((string)(this["OdinDBConnectionStringSMD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOME\\SQLEXPRESS;Initial Catalog=OdinDB;Integrated Security=True;Conne" +
            "ct Timeout=3000")]
        public string OdinDBConnectionString {
            get {
                return ((string)(this["OdinDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mail.smd-baltic.lv")]
        public string SMTPAddress {
            get {
                return ((string)(this["SMTPAddress"]));
            }
            set {
                this["SMTPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9100")]
        public string Printer_Port {
            get {
                return ((string)(this["Printer_Port"]));
            }
            set {
                this["Printer_Port"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("; MultipleActiveResultSets=True")]
        public string OdinDBMARS {
            get {
                return ((string)(this["OdinDBMARS"]));
            }
        }
    }
}
